### ISSUE TITLE
"ui" error

### ISSUE THREAD

**Issue by heytherevampy** [sidmehraajm/RiggingDev#1]
Hello guys,
I have been using VN Magic Tool since a long time now and I really feel that it is one of the best tools.
I saw the video of the updated of the tool and it really looks amazing.
The problem is as shown in the video I am trying to run the script in my Maya 2020 and 2024 but I am getting an error that it cannot find "ui" module in the main folder and when I checked the "ui" file was there on the given path. I also went through the "ui" python file as well and I felt the file is proper. Can you please look into it and let me know. I am also attaching the screenshot for your reference. I am also available anytime if you guys wanna connect and check it out.

Peace!
![uiError_20](https://github.com/sidmehraajm/RiggingDev/assets/156403253/15eccee8-a1c3-4962-84a6-b535e9bea31e)
![uiError_24](https://github.com/sidmehraajm/RiggingDev/assets/156403253/5ca6c0e9-a0de-45eb-9ea3-2b4a8224fbb0)

**Comment by vishal980-glitch** [comment]
Hi @heytherevampy,

Thanks for bringing up the issue. Could you try replacing "backward slash" with "forward slash" in your directory path? This might resolve the problem.

Best,
Vishal

**Comment by heytherevampy** [comment]
Hello @vishal980-glitch ,
I tried doing the same thing but it is not working out.
I am attaching the image for your reference and also @sidmehraajm asked for the screenshot for my file path, I am also attaching the screenshot for that as well.

Thanking you,
Meet Mehta

![uiError_20_02](https://github.com/sidmehraajm/RiggingDev/assets/156403253/32f3f41d-e004-427e-be8b-b3febe34e167)
![uiError_location](https://github.com/sidmehraajm/RiggingDev/assets/156403253/f0c12856-694b-4df0-8394-399d39eb4dfa)

**Comment by sidmehraajm** [comment]
Solved by trying again with path name changed to /

**Comment by EgorDD** [comment]
I don't know how you solved the problem, but Windows doesn't support backslashes in paths. I get this error every time. Perhaps it is easier to make a copy of the script on Windows and test it on a PC rather than telling it on a Mac?

# Error: ModuleNotFoundError: file C:\Users/digor/Desktop/RiggingDev-main /RiggingDev-main/main\ui.py line 2: No module named 'pymel'

I get this error. Moreover, the first and last slash in my script are written correctly. They are replaced by themselves in the error message

**Comment by vishal980-glitch** [comment]
Hi @EgorDD 

It seems there's a path formatting issue in your script, possibly due to mixing slashes (\\,//). 
To fix it, use backslashes for Windows paths and forward slashes for Mac. 

Also, make sure 'pymel' is correctly installed using pip and accessible in your Python environment.

Thanks
